rssFeeds: [
"http://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
"http://news.yahoo.com/rss/stock-markets",
"http://news.yahoo.com/rss/movies",
"http://news.yahoo.com/rss/politics",
"http://news.yahoo.com/rss/world",
"http://news.google.com/?output=rss",
"http://rss.cnn.com/rss/cnn_topstories.rss",
"http://feeds.bbci.co.uk/news/rss.xml",
"http://feeds.bbci.co.uk/news/world/rss.xml",
"http://feeds.bbci.co.uk/news/business/rss.xml",
"http://www.reddit.com/.rss",
"http://news.ycombinator.com/rss",
]

defaultFeeds: [
"http://rss.nytimes.com/services/xml/rss/nyt/Business.xml",
"http://news.yahoo.com/rss/stock-markets",
"http://rss.cnn.com/rss/cnn_topstories.rss",
]